apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: nginx-cm
  name: nginx-cm
data:
  index.html: "hello world"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: nginx-static-volume
          configMap:
            name: nginx-cm
            items:
              - key: "index.html"
                path: "index.html"
      containers:
        - name: nginx
          image: library/nginx:latest
          startupProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15 # force a slow-ish startup, useful for testing timeouts
            periodSeconds: 5
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-static-volume
              mountPath: "/usr/share/nginx/html"
              readOnly: true
