configuration:
  runtime: concord-v2
  dependencies:
    - "mvn://com.walmartlabs.concord.plugins:jsonpath-task:1.31.2-SNAPSHOT"

flows:
  default:
    # inline
    - log: "Inline result: ${jsonPath.readJson(http.asString('https://jsonplaceholder.typicode.com/todos'), '$.[:10].title')}"

    # using the task syntax
    - task: jsonPath
      in:
        action: "readJson"
        src: "${http.asString('https://jsonplaceholder.typicode.com/todos')}"
        path: "$.[:10].title"
      out: result

    - log: "Task syntax result: ${result}"
